---
- name: Install NethServer software repositories
  yum:
    name: http://mirror.nethserver.org/nethserver/nethserver-release-7.rpm

- name: Install NethServer base system
  command: /sbin/nethserver-install

- name: Update system
  yum:
    name: '*'
    state: latest

- name: Copy networks init script
  copy:
    src: nethserver-networks-init
    dest: /var/lib/cloud/scripts/per-instance/
    mode: 0755

- name: Copy system init script
  copy:
    src: nethserver-system-init
    dest: /var/lib/cloud/scripts/per-once/
    mode: 0755

- name: Create systemd override dir for Cockpit
  file:
    path: /etc/systemd/system/cockpit.service.d
    state: directory
    mode: '0755'

- name: Copy systemd override for Cockpit
  copy:
    src: digitalocean.conf
    dest: /etc/systemd/system/cockpit.service.d
    mode: 0644

- name: Remove cloud-init per-once sem
  file:
    path: /var/lib/cloud/sem/config_scripts_per_once.once
    state: absent

- name: Cleanup yum cache
  command: yum clean all
  args:
    warn: false

- name: Cleanup files
  command: "rm -rf {{ item }}"
  args:
    warn: false
  with_items:
    - /root/.ssh/authorized_keys
    - /var/lib/yum/uuid
    - /var/log/nethserver-install.log
    - /var/log/cloud-init.log
    - /var/log/shorewall-init.log
    - /var/log/cloud-init.log
    - /var/log/firewall.log
    - /var/log/shorewall-init.log
    - /var/log/yum.log
    - "/tmp/*"
    - "/var/tmp/*"
    - "/var/log/*.gz"
    - "/var/log/*.[0-9]"
    - "/var/log/*-????????"
    - "/var/lib/cloud/instances/*"
    - "/etc/ssh/*key*"

- name: Clean up ssh revoked keys
  file:
    path: /etc/ssh/revoked_keys
    mode: 0600
    state: touch

# Suggested by https://github.com/digitalocean/marketplace-partners/blob/master/scripts/cleanup.sh
- name: Secure rewrite of the free disk space
  shell: "dd if=/dev/zero of=/zerofile ; sync; rm /zerofile; sync"
  ignore_errors: yes

- name: Truncate lastlog and wtmp
  copy:
    content: ""
    dest: "{{ item }}"
  with_items:
    - /var/log/lastlog
    - /var/log/wtmp

- name: Download DigitalOcean Marketplace Image Validation Tool
  get_url:
    url: https://raw.githubusercontent.com/Amygos/marketplace-partners/ns7_hack/scripts/img_check.sh
    dest: /tmp/
    mode: 0700

- name: Execute DigitalOcean Marketplace Image Validation Tool
  command: /tmp/img_check.sh

- name: Remove DigitalOcean Marketplace Image Validation Tool
  file:
    path: /tmp/img_check.sh
    state: absent
