---
- hosts: all
  become: true
  tasks:
    - name: Install NethServer software repositories
      yum:
        name: http://mirror.nethserver.org/nethserver/nethserver-release-7.rpm
    - name: Install NethServer base system
      command: /sbin/nethserver-install
    - name: Remove yum uuid
      file:
        path: /var/lib/yum/uuid
        state: absent
